name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main  # Adjust if your main branch has a different name

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: PROD_STOCK_OPTION_MANAGER_LANDING

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}  # Your Cloudflare API token
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}  # Your Cloudflare account ID
          projectName: 'stock-option-manager'  # Replace with your project name
          directory: './'  # Path to your static files
          branch: main
